name: Deploy

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Package
        run: dotnet pack
      - name: Publish
        run: dotnet nuget push ./Speck.NugetSandbox/src/Speck.NugetSandbox/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_TOKEN }}
